sudo: false

language: go

go:
  - tip

before_script:
  - echo "machine github.com login $GITHUB_USER password $GITHUB_TOKEN" >> ~/.netrc
  - wget https://github.com/phuslu/goproxy/raw/master/assets/scripts/ci.sh

script:
  - test $TRAVIS_PULL_REQUEST == "false" && bash -x -e ci.sh || go build -v

addons:
  apt:
    packages:
      - p7zip-full

notifications:
  email:
    recipients:
      - phuslu@hotmail.com
    on_success: change
    on_failure: change
